### ISSUE TITLE
bcp --namespace breaks path to import boost_install in Jamroot

### ISSUE THREAD

**Issue by jbmercha** [boostorg/boost#282]
When using bcp.exe to create a boost subset with a new namespace, building the subset is broken because in the Jamfile the import for boost_install has had the "boost_" portion renamed to the new namespace.

```
Build\boost>.\dist\bin\bcp.exe --namespace=myboost --namespace-alias regex log headers predef config build boost_install ..\foo
Build\boost>cd ..\foo
Build\foo>.\bootstrap.bat
Build\foo>.\b2 toolset=msvc-14.1 --with-regex --with-log
boost-install.jam: No such file or directory
Jamroot:307: in boost-install
ERROR: rule "boost-install.boost-install" unknown in module "Jamfile<Build\foo>".
libs\atomic\build\Jamfile.v2:38: in modules.load
```

**Comment by firewave** [comment]
This issue was introduced with Boost 1.70 and prevents us from updating.

**Comment by pdimov** [comment]
This should be fixed with https://github.com/boostorg/boost/commit/d0586e88122f41cd5ac9666db70c37d6f0fc7480.

**Comment by firewave** [comment]
Thanks. I applied the patch locally but I still get the same error.

**Comment by pdimov** [comment]
What command are you using? Note that without https://github.com/boostorg/bcp/pull/5, you need to manually add `headers` and `boost_install` to the `bcp` command.

**Comment by firewave** [comment]
I am using https://github.com/conan-community/conan-boost with `boost:namespace = boost_ns` and `boost:namespace_alias = True`. I will see if I can find the actual commands being used in the output.

**Comment by pdimov** [comment]
Looks like you need to either add `headers` and `boost_install` to https://github.com/conan-community/conan-boost/blob/release/1.70.0/conanfile.py#L366, or patch `bcp` as per the above PR.

**Comment by firewave** [comment]
Thanks a lot - that seems to have done it.

I will open a ticket with the boost-conan project so they are aware.
